name: CI/CD for Flask App

on:
  push:
    branches: [ "main", "master", "feature/flask-app" ]
  pull_request:
    branches: [ "main", "master", "feature/flask-app" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: List files
        run: echo "Hello from CI"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install flake8
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t flask-app:latest .
          docker tag flask-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

      - name: Deploy to production
        run: |
          echo "Deploying Flask app to production..."
          echo "Docker image: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}"
          # Add your actual deployment commands here
          # For example: kubectl, docker-compose, or cloud provider CLI commands